const num = 6
try{
    num = 'hi';
} catch(err){
    console.error(err)
}